config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :direct_messages
  devise_for :users
  match 'download',to: "home#download_pdf" , as: 'download', via: :get

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  match "/404", to: "errors#not_found", :via => [:get, :post]
  match "/422", to: "errors#unacceptable", :via => [:get, :post]
  match "/500", to: "errors#internal_server_error", :via => [:get, :post]
  # 301 redirect from old URLs
  #match "/old_path_to_posts/:id", to: redirect("/posts/%{id}s"), :via => [:get, :post]

    # Force www redirect
  # Start server with rails s -p 3000 -b lvh.me
  # Then go to http://www.lvh.me:3000
  constraints(host: /^(?!www\.)/i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host = "www.#{uri.host}" }.to_s
    }, :via => [:get, :post]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  include SessionsHelper

  def default_url_options
    { host: ENV['HOST'] || 'localhost:3000' }
  end

  # def default_url_options
  #   if Rails.env.production?
  #     { host: "tesnorcarly.herokuapp.com" }
  #   else
  #     {}
  #   end
  # end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController
  protect_from_forgery
  #before_action :authenticate_user!
  before_action :set_direct_message, only: [:show, :edit, :update, :destroy]

  # GET /direct_messages
  # GET /direct_messages.json
  def index
    @direct_messages = DirectMessage.all
  end

  # GET /direct_messages/1
  # GET /direct_messages/1.json
  def show
  end

  # GET /direct_messages/new
  def new
    @direct_message = DirectMessage.new
  end

  # GET /direct_messages/1/edit
  def edit
  end

  # POST /direct_messages
  # POST /direct_messages.json
  def create
    @direct_message = DirectMessage.new(direct_message_params)

    respond_to do |format|
      if @direct_message.save
        format.html { redirect_to root_path, notice: 'message was successfully sent.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @direct_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direct_messages/1
  # PATCH/PUT /direct_messages/1.json
  def update
    respond_to do |format|
      if @direct_message.update(direct_message_params)
        format.html { redirect_to @direct_message, notice: 'Direct message was successfully updated.' }
        format.json { render :show, status: :ok, location: @direct_message }
      else
        format.html { render :edit }
        format.json { render json: @direct_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direct_messages/1
  # DELETE /direct_messages/1.json
  def destroy
    @direct_message.destroy
    respond_to do |format|
      format.html { redirect_to direct_messages_url, notice: 'Direct message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direct_message
      @direct_message = DirectMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def direct_message_params
      params.require(:direct_message).permit(:name, :mail, :subject, :dm)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   end

   def download_pdf
    send_file(
      "#{Rails.root}/public/resume.pdf",
      filename: "carly_tesnor_resume.pdf",
      type: "application/pdf"
    )
  end
  def all_project
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/direct_messages_helper.rb
module DirectMessagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
      # avec une image dans vos assets ou une url absolue
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/direct_messages/_form.html.erb
<%= form_with(model: direct_message, local: true) do |form| %>
  <% if direct_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(direct_message.errors.count, "error") %> prohibited this direct_message from being saved:</h2>

      <ul>
        <% direct_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
                          <div class="contact-info">
                              <div class="row">
                                <div class="form-group col-sm-6">
                                 
                                  <%= form.text_field :name, :required=>"", :placeholder =>"Name*"%>
                                </div>
                                <div class="form-group col-sm-6">
                                
                                   <%= form.email_field :mail, :required=>"", :placeholder =>"Email*"%>
                                </div>
                                <div class="form-group col-sm-12">
                                  
                                   <%= form.text_field :subject, :placeholder =>"Subject (Optinal)"%>
                                </div>
                                <div class="form-group col-sm-12">
                                 
                                   <%= form.text_area :Dm, :required=>"", :placeholder =>"Message*" %>
                                </div>
                                <div class="col-sm-12"><%= form.submit "Contact me", class: "btn"%></div>
                              </div>
                            </form>
                          </div>
                        </div>
<% end %>

app/views/direct_messages/edit.html.erb
<h1>Editing Direct Message</h1>

<%= render 'form', direct_message: @direct_message %>

<%= link_to 'Show', @direct_message %> |
<%= link_to 'Back', direct_messages_path %>

app/views/direct_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Direct Messages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Subject</th>
      <th>Dm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direct_messages.each do |direct_message| %>
      <tr>
        <td><%= direct_message.name %></td>
        <td><%= direct_message.mail %></td>
        <td><%= direct_message.subject %></td>
        <td><%= direct_message.dm %></td>
        <td><%= link_to 'Show', direct_message %></td>
        <td><%= link_to 'Edit', edit_direct_message_path(direct_message) %></td>
        <td><%= link_to 'Destroy', direct_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direct Message', new_direct_message_path %>

app/views/direct_messages/new.html.erb
<h1>Direct Message</h1>

<%= render 'form', direct_message: @direct_message %>

<%= link_to 'Back', direct_messages_path %>

app/views/direct_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @direct_message.name %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @direct_message.mail %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @direct_message.subject %>
</p>

<p>
  <strong>Dm:</strong>
  <%= @direct_message.dm %>
</p>

<%= link_to 'Edit', edit_direct_message_path(@direct_message) %> |
<%= link_to 'Back', direct_messages_path %>

app/views/home/all_project.html.erb
 <div class="pagepiling">
      <div data-anchor="page1" class="pp-scrollable text-white section section-1">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project1.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a class="" href="project-detail.html">
                          <span class="project-number">01</span>
                          <h2 class="project-title">Abstract Skat</h2>
                          <div class="project-category">Illustration</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page2" class="pp-scrollable text-white section section-2">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project2.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">02</span>
                          <h2 class="project-title">Borato Prism</h2>
                          <div class="project-category">Branding</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page3" class="pp-scrollable text-white section section-3">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project3.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">03</span>
                          <h2 class="project-title">Brole Mobile App</h2>
                          <div class="project-category">Mobile Design</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page4" class="pp-scrollable text-white section section-4">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project4.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">04</span>
                          <h2 class="project-title">Bauhaus Studio</h2>
                          <div class="project-category">House Design</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page5" class="pp-scrollable text-white section section-5">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project5.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">05</span>
                          <h2 class="project-title">Riding Bicycle </h2>
                          <div class="project-category">Illustration</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page6" class="pp-scrollable text-white section section-6">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project6.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">06</span>
                          <h2 class="project-title">Android App</h2>
                          <div class="project-category">Mobile Design</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div data-anchor="page7" class="pp-scrollable text-white section section-7">
        <div class="scroll-wrap">
          <div class="section-bg" style="background-image:url(images/bg/project7.jpg);"></div>
          <div class="scrollable-content">
            <div class="vertical-centred v2">
              <div class="boxed boxed-inner">
                <div class="boxed">
                  <div class="container">
                    <div class="intro">
                      <div class="project-detail-row">
                        <a href="project-detail.html">
                          <span class="project-number">07</span>
                          <h2 class="project-title">Coffee breakfast</h2>
                          <div class="project-category">Design</div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= meta_title %></title>
	<meta name="description" content="<%= meta_description %>">

	<!-- Facebook Open Graph data -->
	<meta property="og:title" content="<%= meta_title %>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="<%= request.original_url %>" />
	<meta property="og:image" content="<%= meta_image %>" />
	<meta property="og:description" content="<%= meta_description %>" />
	<meta property="og:site_name" content="<%= meta_title %>" />

	<!-- Twitter Card data -->
	<meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
	<meta name="twitter:title" content="<%= meta_title %>">
	<meta name="twitter:description" content="<%= meta_description %>">
	<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
	<meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="manifest" href="/manifest.json" />
     <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"
      integrity="sha384-i1LQnF23gykqWXg6jxC2ZbCbUMxyw5gLZY6UiUS98LYV5unm8GWmfkIS6jqJfb4E"
      crossorigin="anonymous"
    />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
  
  <div class="copy-bottom white boxed">© CRT <%= Date.today.year %>.</div>
    <div class="social-list social-list-bottom boxed">
         <a href="https://web.facebook.com/carlytesnor?ref=bookmarks"> <i class="fab fa-facebook-f "> </i></a>
          <a href="https://twitter.com/TesnorC"> <i class="fab fa-twitter "></i></a>
          <a href="https://www.linkedin.com/in/carly-r-tesnor-633736160/"> <i class="fab fa-linkedin "></i></a>
          <a href="https://github.com/Carly509"> <i class="fab fa-github "></i></a>
      </div>
 

	<div>
		<% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
	</div>

    <%= yield %>



		<!-- jQuery -->

<script src="js/jquery.min.js"></script>
<script src="js/smoothscroll.js"></script>
<script src="js/animsition.js"></script>
<script src="js/jquery.validate.min.js"></script>
<script src="js/jquery.magnific-popup.min.js"></script>
<script src="js/jquery.pagepiling.min.js"></script>

<!-- Scripts -->
<script src="js/scripts.js"></script> 

  </body>
</html>